<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Sky Stebnicki'))->setSeparator(' - ')->setAutoEscape(true) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js') ?>

    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
              <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<?php echo $this->url('apphome') ?>"><?php echo $this->translate('Sky Stebnicki') ?></a>
              </div>
              <div class="navbar-collapse collapse">
                <?php echo $this->navigation('CmsNavigation')->menu()->setUlClass('nav navbar-nav'); ?>
                <form class="navbar-form navbar-right">
                  <div class="form-group">
                    <input type="text" placeholder="Email" class="form-control">
                  </div>
                  <div class="form-group">
                    <input type="password" placeholder="Password" class="form-control">
                  </div>
                  <button type="submit" class="btn btn-success">Sign in</button>
                </form>
              </div><!--/.navbar-collapse -->
            </div>
        </div>
       
        <div class="container" id="main">
           	<?php echo $this->content; ?>

        </div> <!-- /container -->

        <div class="container">
            <footer>
                <p>&copy; 2012 - <?php echo date('Y') ?> by Sky Stebnicki. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
		</div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
